version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=nguyennt63
    volumes:
      - /docker/configs/sentinel:/usr/local/etc/redis
    networks:
      - app-tier
    ports:
      - '6379:6379'

  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=nguyennt63
      - REDIS_PASSWORD=nguyennt63
      - REDIS_SLAVE_READ_ONLY=no
    volumes:
      - /docker/configs/sentinel:/usr/local/etc/redis
    ports:
      - '6378:6379'
    depends_on:
      - redis
    networks:
      - app-tier

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=nguyennt63
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    volumes:
      - /docker/configs/sentinel:/usr/local/etc/redis
    networks:
      - app-tier


      